### ISSUE TITLE
Lab10 Peer Review, by s314700

### ISSUE THREAD

**Issue by YaldaMobargha** [AugustAasvaer/computational_intelligence#3]
Hello.
I'm reviewing your code for the lab number 10.
First, good job, it seems that you worked hard and tried a lot also I liked that you showed the results with plots and the final results look good, additionally specifying the link of your reference is a good idea.
I only found a little problem, which is a typo, you wrote "baord" instead of the board in the "evaluate_position" function, also I have some suggestions for the future, for example indicating the results in percentage format is more comprehensible, and also adding comments in the code or a more comprehensive readme file would make the understanding stage much quicker.

I hope the review will be useful and Good luck with the exam.

**Comment by AugustAasvaer** [comment]
Thank you very much for your review!
